### PR TITLE
Add nix flake.

### PR DESCRIPTION
**Pull request by damianfral**
This PR adds a flake.nix file (https://www.tweag.io/blog/2020-05-25-flakes/). I've renamed default.nix arguments to `final` and `prev` as `nix flake check` requires.

### CODE REVIEW

**Comment by anmonteiro** [comment]
Hey! I'm not opposed to adding a flake, but I don't know how to use them yet. I've read a little on them but IIRC there isn't yet a stable version of Nix that has this functionality? Could you point me to a source that tells me I'm wrong?

Regarding this specific PR, there are some unnecessary changes in `default.nix` that should be reverted.

**Comment by damianfral** [comment]
Hi @anmonteiro!

> Hey! I'm not opposed to adding a flake, but I don't know how to use them yet. 

You can follow the posts from Tweag's blog (https://www.tweag.io/blog/2020-05-25-flakes/) or this shorter tutorial, https://zimbatm.com/NixFlakes.

> I've read a little on them but IIRC there isn't yet a stable version of Nix that has this functionality? Could you point me to a source that tells me I'm wrong?

You are right. Anyway, this PR should not break previous workflows, it just adds a new file and rename the arguments of the overlay (default.nix).

> Regarding this specific PR, there are some unnecessary changes in `default.nix` that should be reverted.

I think I just changed self/super to final/prev. :)

**Comment by damianfral** [comment]
hey @anmonteiro, I've rebased this branch on top of master. And btw, I'm not sure, but I think flakes might be already merged into master, https://github.com/NixOS/nixpkgs/search?q=flakes&type=commits.

**Comment by anmonteiro** [comment]
> I think I just changed self/super to final/prev. :)

Indeed. Please revert.


Trying to think a little more about this, I'm not necessarily opposed to merging it, but there are a few things I'd like to clarify + a question from me:

1. Could you state your goals in getting a flake.nix in this repo? are you just interested in getting these overlays for your own use?
2. tangentially related to 1., these overlays are originally intended for my personal use, and I may break / upgrade any dependencies without any regard for who is also depending on them.
3. Note that, while I'm not opposed to exposing the `bs-platform` package, I'm not planning on updating that specific packaging of BuckleScript going forward, as I've switched to my own version that is compatible with the OCaml ecosystem (and the dune build system).

**Comment by damianfral** [comment]
> Indeed. Please revert.

`nix flake check` throws an error if overlays don't name arguments that way.

> Could you state your goals in getting a flake.nix in this repo? are you just interested in getting these overlays for your own use?

I'm just interested in the bucklescript stuff. Since I'm using flakes for my repos, it's easier for me to work with dependencies. I've used different approaches (like niv) but flakes is gonna be the standard.

> Note that, while I'm not opposed to exposing the bs-platform package, I'm not planning on updating that specific packaging of BuckleScript going forward, as I've switched to my own version that is compatible with the OCaml ecosystem (and the dune build system).

No problem. I was expecting your repo to become sort of a bucklescript/ocaml overlay. If that's not your purpose, I can work on my own fork independently (if you don't have any problem with that, of course). Anyway, thanks @anmonteiro :)

**Comment by anmonteiro** [comment]
We added nix flakes recently in #112 and #116 so I'm going to close this one.

**Pull request closed without merging**
