### PR TITLE
new sources

### PR DESCRIPTION
**Pull request by anmonteiro**

### CODE REVIEW

**Comment by ulrikstrid** [comment]
I'm about to do a release of jose that doesn't fail here, you can mark it as failing for now and I'll open a PR when I have a release

**Comment by ulrikstrid** [comment]
https://github.com/ocaml/opam-repository/pull/18588

**Comment by anmonteiro** [comment]
wanna push it to this branch?

**Comment by ulrikstrid** [comment]
Sure

**Pull request merged**
